# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

project_name: backlog

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w

# https://github.com/goreleaser/example-supply-chain
checksum:
  name_template: "checksums.txt"

report_sizes: true

sboms:
  - artifacts: archive
  - id: source # Two different sbom configurations need two different IDs
    artifacts: source

kos:
  - repositories:
      - ghcr.io/veggiemonk/backlog
    creation_time: "{{.CommitTimestamp}}"
    base_image: "cgr.dev/chainguard/static:latest"
    tags:
      - "{{.Version}}"
      - latest
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"
      org.opencontainers.image.description: |
        Backlog is a zero-configuration task manager written in Go where tasks live inside a Git repository. It leverages plain Markdown files for task storage and a comprehensive command-line interface (CLI) for interaction. This design makes it exceptionally well-suited for AI agents thanks to its MCP (Model Context Protocol) integration.
    annotations:
      "index:org.opencontainers.image.description": |
        Backlog is a zero-configuration task manager written in Go where tasks live inside a Git repository. It leverages plain Markdown files for task storage and a comprehensive command-line interface (CLI) for interaction. This design makes it exceptionally well-suited for AI agents thanks to its MCP (Model Context Protocol) integration.
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

release:
  footer: >-

    **Container Image** in [gcr.io/veggiemonk/backlog](https://gcr.io/veggiemonk/backlog): `gcr.io/veggiemonk/backlog:{{ .Tag }}`

    **Full Changelog**: https://github.com/veggiemonk/backlog/compare/{{ .PreviousTag }}...{{ .Tag }}

    **Open Source Insights**: [{{ .Tag }}](https://deps.dev/go/github.com%2Fveggiemonk%2Fbacklog/{{ .Tag }}) (compare to [{{ .PreviousTag }}](https://deps.dev/go/github.com%2Fveggiemonk%2Fbacklog/{{ .PreviousTag }}/compare?v2={{ .Tag }}))

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
