baseURL = 'https://veggiemonk.github.io/backlog'
languageCode = 'en-us'
title = 'Backlog MCP Documentation'

# Hugo configuration
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[module]
[[module.imports]]
    path = "github.com/google/docsy"
    disable = false

[params]
# General settings
description = "Zero-configuration task manager for developers and AI agents"
keywords = ["task management", "cli", "ai agents", "mcp", "golang", "git"]

# GitHub integration
github_repo = 'https://github.com/veggiemonk/backlog'
github_branch = 'main'

# Docsy UI configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Set to true to hide the sidebar search box
sidebar_search_disable = false

# Docsy search configuration
[params.search]
# Enable search functionality
enable = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = 'github'
lineNos = true
anchorLineNos = false
codeFences = true
guessSyntax = false
# hl_Lines = ''
noClasses = false
noHl = false
tabWidth = 2

[outputs]
home = ['HTML', 'RSS', 'JSON']
page = ['HTML']
section = ['HTML', 'RSS']

[outputFormats.SearchIndex]
mediaType = 'application/json'
baseName = 'search'
isPlainText = true
notAlternative = true

# Main menu configuration
[[menu.main]]
name = "Home"
url = "/"
weight = 10

[[menu.main]]
name = "Getting Started"
url = "/getting-started/"
weight = 20

[[menu.main]]
name = "CLI Reference"
url = "/cli/"
weight = 30

[[menu.main]]
name = "AI Integration"
url = "/ai-integration/"
weight = 40

[[menu.main]]
name = "Development"
url = "/development/"
weight = 50

[[menu.main]]
name = "About"
url = "/about/"
weight = 60
