baseURL = 'https://veggiemonk.github.io/backlog'
languageCode = 'en-us'
title = 'Backlog MCP Documentation'

# Hugo configuration
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Language configuration
[languages]

[languages.en]
languageName = "English"
title = "backlog MCP server"
[languages.en.params]
description = "Backlog is a zero-configuration task manager written in Go where tasks live inside a Git repository. It leverages plain Markdown files for task storage and a comprehensive command-line interface (CLI) for interaction. This design makes it exceptionally well-suited for AI agents thanks to its MCP (Model Context Protocol) integration."

[module]
[module.hugoVersion]
extended = true
min = "0.146.0"
[[module.imports]]
path = "github.com/google/docsy"
disable = false

[[links.user]]
name = "GitHub Discussions"
url = "https://github.com/veggiemonk/backlog/discussions"
icon = "fab fa-github"
desc = "Discussion and help from your fellow users"

[[links.developer]]
name = "GitHub"
url = "https://github.com/veggiemonk/backlog"
icon = "fab fa-github"
desc = "Development takes place here!"

[[links.developer]]
name = "Issues"
url = "https://github.com/veggiemonk/backlog/issues"
icon = "fa fa-bug"
desc = "Report bugs and request features"

[params]
# General settings
description = "Zero-configuration task manager for developers and AI agents"
keywords = ["task management", "cli", "ai agents", "mcp", "golang", "git"]

# Logo configuration - simple clipboard emoji logo
[params.logos]
navbar = "/images/logo.svg"

# GitHub integration
github_repo = 'https://github.com/veggiemonk/backlog'
github_branch = 'main'

# Docsy UI configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Set to true to hide the sidebar search box
sidebar_search_disable = false

# Docsy search configuration
[params.search]
# Enable search functionality
enable = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = 'github'
lineNos = true
anchorLineNos = false
codeFences = true
guessSyntax = false
# hl_Lines = ''
noClasses = false
noHl = false
tabWidth = 2

[outputs]
home = ['HTML', 'RSS', 'JSON']
page = ['HTML']
section = ['HTML', 'RSS']

[outputFormats.SearchIndex]
mediaType = 'application/json'
baseName = 'search'
isPlainText = true
notAlternative = true

# Main menu configuration
[[menu.main]]
name = "Home"
url = "/"
weight = 10

[[menu.main]]
name = "Getting Started"
url = "/getting-started/"
weight = 20

[[menu.main]]
name = "CLI Reference"
url = "/cli/"
weight = 30

[[menu.main]]
name = "AI Integration"
url = "/ai-integration/"
weight = 40

[[menu.main]]
name = "Development"
url = "/development/"
weight = 50

[[menu.main]]
name = "About"
url = "/about/"
weight = 60
